<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Specialite;
use App\Models\Formation;

class OrientationSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            [
                'specialite' => [
                    'nom'         => 'Informatique & Intelligence Artificielle',
                    'description' => 'Programmation, algorithmes, machine learning et développement de systèmes intelligents. Le domaine le plus porteur de la décennie.',
                    'domaine'     => 'Technologie',
                    'icon'        => '💻',
                    'color'       => 'indigo',
                ],
                'formations' => [
                    [
                        'nom'              => 'Licence en Génie Logiciel',
                        'etablissement'    => 'ESPRIT',
                        'ville'            => 'Tunis',
                        'duree'            => '3 ans',
                        'niveau'           => 'Licence',
                        'description'      => 'Formation complète en développement logiciel couvrant les langages modernes (Java, Python, JavaScript), les bases de données, le cloud et les méthodes agiles.',
                        'debouches'        => 'Développeur Full-Stack, Ingénieur DevOps, Chef de projet technique, Consultant IT, Freelance international.',
                        'conditions_acces' => 'Baccalauréat scientifique ou technique. Concours d\'entrée ou dossier scolaire. Moyenne en mathématiques ≥ 12/20.',
                        'salaire_min'      => '1 800 DT',
                        'salaire_max'      => '4 500 DT',
                        'secteur'          => 'Tech / Startup',
                        'icon'             => '🖥️',
                        'score_matching'   => 95,
                    ],
                    [
                        'nom'              => 'Ingénierie en Intelligence Artificielle',
                        'etablissement'    => 'SUP\'COM',
                        'ville'            => 'Tunis',
                        'duree'            => '5 ans',
                        'niveau'           => 'Ingénierie',
                        'description'      => 'Cycle ingénieur spécialisé en IA, deep learning, traitement du langage naturel (NLP), vision par ordinateur et intégration de systèmes intelligents.',
                        'debouches'        => 'Data Scientist, Ingénieur IA, Chercheur en ML, Architect solutions IA, Consultant IA.',
                        'conditions_acces' => 'Bac + 2 prépa ou concours national. Excellents résultats en mathématiques et physique.',
                        'salaire_min'      => '3 200 DT',
                        'salaire_max'      => '7 000 DT',
                        'secteur'          => 'IA / Recherche',
                        'icon'             => '🤖',
                        'score_matching'   => 91,
                    ],
                    [
                        'nom'              => 'Master en Cybersécurité',
                        'etablissement'    => 'ISI',
                        'ville'            => 'Tunis',
                        'duree'            => '2 ans',
                        'niveau'           => 'Master',
                        'description'      => 'Formation spécialisée en sécurité des systèmes d\'information, cryptographie, tests de pénétration, forensics et gouvernance de la sécurité.',
                        'debouches'        => 'Expert Cybersécurité, Pentester, RSSI, Analyste SOC, Consultant sécurité.',
                        'conditions_acces' => 'Licence en informatique ou équivalent. Dossier académique solide.',
                        'salaire_min'      => '2 500 DT',
                        'salaire_max'      => '6 000 DT',
                        'secteur'          => 'Sécurité / Banque',
                        'icon'             => '🔒',
                        'score_matching'   => 88,
                    ],
                ],
            ],
            [
                'specialite' => [
                    'nom'         => 'Data Science & Big Data',
                    'description' => 'Analyse de données massives, statistiques avancées, visualisation et prise de décision data-driven pour toutes les industries.',
                    'domaine'     => 'Technologie',
                    'icon'        => '📊',
                    'color'       => 'cyan',
                ],
                'formations' => [
                    [
                        'nom'              => 'Master Data Science & Analytics',
                        'etablissement'    => 'ENSI',
                        'ville'            => 'La Manouba',
                        'duree'            => '2 ans',
                        'niveau'           => 'Master',
                        'description'      => 'Formation d\'excellence alliant statistiques, programmation Python/R, machine learning, Big Data (Spark, Hadoop) et business intelligence.',
                        'debouches'        => 'Data Analyst, Data Engineer, Business Analyst, Responsable BI, Data Scientist.',
                        'conditions_acces' => 'Licence en informatique, mathématiques ou statistiques. Bonne maîtrise de Python ou R.',
                        'salaire_min'      => '2 400 DT',
                        'salaire_max'      => '5 500 DT',
                        'secteur'          => 'Finance / Télécom',
                        'icon'             => '📈',
                        'score_matching'   => 89,
                    ],
                    [
                        'nom'              => 'Licence en Statistiques Appliquées',
                        'etablissement'    => 'ISSAT',
                        'ville'            => 'Sousse',
                        'duree'            => '3 ans',
                        'niveau'           => 'Licence',
                        'description'      => 'Fondements des probabilités, inférence statistique, analyse multivariée et introduction à la data science pour une carrière dans l\'analyse quantitative.',
                        'debouches'        => 'Statisticien, Actuaire junior, Analyste marché, Chargé d\'études.',
                        'conditions_acces' => 'Baccalauréat scientifique. Moyenne supérieure à 10/20.',
                        'salaire_min'      => '1 500 DT',
                        'salaire_max'      => '3 200 DT',
                        'secteur'          => 'Assurance / Recherche',
                        'icon'             => '🔢',
                        'score_matching'   => 82,
                    ],
                    [
                        'nom'              => 'Ingénierie en Systèmes d\'Information',
                        'etablissement'    => 'ENIS',
                        'ville'            => 'Sfax',
                        'duree'            => '5 ans',
                        'niveau'           => 'Ingénierie',
                        'description'      => 'Conception et gestion de systèmes d\'information complexes, architecture cloud, ERP, CRM et transformation numérique des entreprises.',
                        'debouches'        => 'Architecte SI, Ingénieur ERP, Chef de projet IT, DSI adjoint.',
                        'conditions_acces' => 'Concours national. Bac + 2 prépa scientifique.',
                        'salaire_min'      => '2 800 DT',
                        'salaire_max'      => '5 800 DT',
                        'secteur'          => 'Entreprise / Industrie',
                        'icon'             => '🗄️',
                        'score_matching'   => 86,
                    ],
                ],
            ],
            [
                'specialite' => [
                    'nom'         => 'Médecine & Sciences de la Santé',
                    'description' => 'Formation aux métiers de la santé humaine, de la recherche biomédicale au soin clinique, avec des débouchés stables et reconnus.',
                    'domaine'     => 'Santé',
                    'icon'        => '🩺',
                    'color'       => 'green',
                ],
                'formations' => [
                    [
                        'nom'              => 'Doctorat en Médecine Générale',
                        'etablissement'    => 'Faculté de Médecine de Tunis',
                        'ville'            => 'Tunis',
                        'duree'            => '7 ans',
                        'niveau'           => 'Doctorat',
                        'description'      => 'Formation médicale complète : sciences fondamentales, clinique hospitalière, stages en CHU. Couvre toutes les spécialités médicales de base.',
                        'debouches'        => 'Médecin généraliste, Médecin spécialiste (après résidanat), Médecin urgentiste, Chercheur médical.',
                        'conditions_acces' => 'Baccalauréat sciences expérimentales ou mathématiques. Concours national très sélectif (classement).',
                        'salaire_min'      => '2 200 DT',
                        'salaire_max'      => '8 000 DT',
                        'secteur'          => 'Santé Publique / Privé',
                        'icon'             => '🏥',
                        'score_matching'   => 78,
                    ],
                    [
                        'nom'              => 'Licence en Sciences Infirmières',
                        'etablissement'    => 'ISSSI',
                        'ville'            => 'Ariana',
                        'duree'            => '3 ans',
                        'niveau'           => 'Licence',
                        'description'      => 'Formation pratique et théorique aux soins infirmiers, hygiène hospitalière, pharmacologie de base et techniques d\'urgence.',
                        'debouches'        => 'Infirmier diplômé, Infirmier anesthésiste, Coordinateur soins, Infirmier libéral.',
                        'conditions_acces' => 'Baccalauréat sciences. Dossier médical. Entretien de motivation.',
                        'salaire_min'      => '1 200 DT',
                        'salaire_max'      => '2 800 DT',
                        'secteur'          => 'Hôpital / Clinique',
                        'icon'             => '💊',
                        'score_matching'   => 74,
                    ],
                    [
                        'nom'              => 'Licence en Biologie Médicale',
                        'etablissement'    => 'FSB',
                        'ville'            => 'Bizerte',
                        'duree'            => '3 ans',
                        'niveau'           => 'Licence',
                        'description'      => 'Biochimie, microbiologie, hématologie et techniques d\'analyses médicales. Prépare aux laboratoires cliniques et à la recherche biomédicale.',
                        'debouches'        => 'Technicien de laboratoire, Analyste biomédical, Chercheur junior.',
                        'conditions_acces' => 'Baccalauréat sciences expérimentales. Moyenne ≥ 11/20.',
                        'salaire_min'      => '1 400 DT',
                        'salaire_max'      => '3 000 DT',
                        'secteur'          => 'Laboratoire / Pharma',
                        'icon'             => '🧬',
                        'score_matching'   => 71,
                    ],
                ],
            ],
            [
                'specialite' => [
                    'nom'         => 'Génie Civil & Architecture',
                    'description' => 'Conception, calcul et réalisation d\'ouvrages, bâtiments et infrastructures urbaines. Combinant créativité et maîtrise technique.',
                    'domaine'     => 'Sciences',
                    'icon'        => '🏗️',
                    'color'       => 'amber',
                ],
                'formations' => [
                    [
                        'nom'              => 'Ingénierie en Génie Civil',
                        'etablissement'    => 'ENIT',
                        'ville'            => 'Tunis',
                        'duree'            => '5 ans',
                        'niveau'           => 'Ingénierie',
                        'description'      => 'Mécanique des structures, béton armé, géotechnique, hydraulique et gestion de projets de construction. Prépare aux grands chantiers publics et privés.',
                        'debouches'        => 'Ingénieur BTP, Chef de chantier, Bureau d\'études, Responsable travaux.',
                        'conditions_acces' => 'Concours national. Bac + 2 prépa math-physique.',
                        'salaire_min'      => '2 000 DT',
                        'salaire_max'      => '5 000 DT',
                        'secteur'          => 'BTP / Infrastructures',
                        'icon'             => '🏛️',
                        'score_matching'   => 80,
                    ],
                    [
                        'nom'              => 'Diplôme National d\'Architecte',
                        'etablissement'    => 'ENAU',
                        'ville'            => 'Tunis',
                        'duree'            => '6 ans',
                        'niveau'           => 'Master',
                        'description'      => 'Conception architecturale, urbanisme, histoire de l\'architecture, atelier de projet et représentation numérique (BIM, CAO).',
                        'debouches'        => 'Architecte diplômé, Urbaniste, Designer d\'intérieur, Chef de projet immobilier.',
                        'conditions_acces' => 'Baccalauréat toutes séries. Concours d\'entrée sur dossier et épreuves de dessin.',
                        'salaire_min'      => '1 800 DT',
                        'salaire_max'      => '5 500 DT',
                        'secteur'          => 'Immobilier / Public',
                        'icon'             => '🏠',
                        'score_matching'   => 77,
                    ],
                    [
                        'nom'              => 'Licence en Topographie',
                        'etablissement'    => 'ISET Charguia',
                        'ville'            => 'Tunis',
                        'duree'            => '3 ans',
                        'niveau'           => 'Licence',
                        'description'      => 'Mesures terrestres, cartographie numérique, SIG (Systèmes d\'Information Géographique), cadastre et photogrammétrie.',
                        'debouches'        => 'Topographe, Géomètre expert, Technicien SIG, Chargé de cadastre.',
                        'conditions_acces' => 'Baccalauréat scientifique. Admis sur dossier ou concours.',
                        'salaire_min'      => '1 400 DT',
                        'salaire_max'      => '3 000 DT',
                        'secteur'          => 'Foncier / Aménagement',
                        'icon'             => '🗺️',
                        'score_matching'   => 68,
                    ],
                ],
            ],
            [
                'specialite' => [
                    'nom'         => 'Gestion & Sciences Économiques',
                    'description' => 'Pilotage d\'entreprise, finance, marketing et stratégie pour comprendre et diriger les organisations dans un monde globalisé.',
                    'domaine'     => 'Gestion',
                    'icon'        => '📈',
                    'color'       => 'violet',
                ],
                'formations' => [
                    [
                        'nom'              => 'Licence en Comptabilité & Finance',
                        'etablissement'    => 'FSEG',
                        'ville'            => 'Tunis',
                        'duree'            => '3 ans',
                        'niveau'           => 'Licence',
                        'description'      => 'Comptabilité générale et analytique, fiscalité tunisienne, analyse financière, contrôle de gestion et normes IFRS.',
                        'debouches'        => 'Comptable, Expert-comptable (après ICOMP), Contrôleur de gestion, Auditeur.',
                        'conditions_acces' => 'Baccalauréat économie-gestion ou sciences. Admission sur dossier.',
                        'salaire_min'      => '1 400 DT',
                        'salaire_max'      => '4 000 DT',
                        'secteur'          => 'Finance / Audit',
                        'icon'             => '💰',
                        'score_matching'   => 72,
                    ],
                    [
                        'nom'              => 'Master en Management des Entreprises',
                        'etablissement'    => 'IHEC Carthage',
                        'ville'            => 'Tunis',
                        'duree'            => '2 ans',
                        'niveau'           => 'Master',
                        'description'      => 'Leadership, stratégie d\'entreprise, behavior organizational, gestion des ressources humaines et développement durable des organisations.',
                        'debouches'        => 'Manager, DRH, Directeur commercial, Entrepreneur, Consultant en stratégie.',
                        'conditions_acces' => 'Licence en gestion ou équivalent. Entretien de motivation.',
                        'salaire_min'      => '2 000 DT',
                        'salaire_max'      => '5 000 DT',
                        'secteur'          => 'Industries / Services',
                        'icon'             => '🎯',
                        'score_matching'   => 76,
                    ],
                    [
                        'nom'              => 'Licence en Marketing Digital',
                        'etablissement'    => 'ESCT',
                        'ville'            => 'La Manouba',
                        'duree'            => '3 ans',
                        'niveau'           => 'Licence',
                        'description'      => 'Marketing stratégique, e-commerce, SEO/SEM, réseaux sociaux, création de contenu et analytics pour piloter la présence digitale des marques.',
                        'debouches'        => 'Responsable marketing digital, Community manager, Chef de produit, Growth hacker.',
                        'conditions_acces' => 'Baccalauréat toutes séries. Admis sur dossier.',
                        'salaire_min'      => '1 300 DT',
                        'salaire_max'      => '3 500 DT',
                        'secteur'          => 'Médias / E-commerce',
                        'icon'             => '📱',
                        'score_matching'   => 70,
                    ],
                ],
            ],
            [
                'specialite' => [
                    'nom'         => 'Design & Arts Créatifs',
                    'description' => 'Expression artistique, design visuel, UX/UI et communication créative pour concevoir des expériences mémorables.',
                    'domaine'     => 'Arts',
                    'icon'        => '🎨',
                    'color'       => 'violet',
                ],
                'formations' => [
                    [
                        'nom'              => 'Licence en Design Graphique',
                        'etablissement'    => 'ISAD',
                        'ville'            => 'Tunis',
                        'duree'            => '3 ans',
                        'niveau'           => 'Licence',
                        'description'      => 'Typographie, identité visuelle, illustration numérique, motion design et production créative avec Adobe Suite et Figma.',
                        'debouches'        => 'Graphiste, Directeur artistique, Designer de marque, Illustrateur freelance.',
                        'conditions_acces' => 'Baccalauréat toutes séries. Portfolio artistique + entretien.',
                        'salaire_min'      => '1 100 DT',
                        'salaire_max'      => '3 000 DT',
                        'secteur'          => 'Agences / Presse',
                        'icon'             => '🖌️',
                        'score_matching'   => 73,
                    ],
                    [
                        'nom'              => 'Master UX Design & Product',
                        'etablissement'    => 'Polytechnique Privée',
                        'ville'            => 'Tunis',
                        'duree'            => '2 ans',
                        'niveau'           => 'Master',
                        'description'      => 'Recherche utilisateur, wireframing, prototypage Figma, tests d\'usage, design system et collaboration avec les équipes de développement.',
                        'debouches'        => 'UX Designer, Product Designer, UI Lead, Design Sprint facilitator.',
                        'conditions_acces' => 'Licence en design, informatique ou communication. Effraction sur portfolio.',
                        'salaire_min'      => '2 000 DT',
                        'salaire_max'      => '4 500 DT',
                        'secteur'          => 'Tech / Startups',
                        'icon'             => '📐',
                        'score_matching'   => 81,
                    ],
                    [
                        'nom'              => 'Licence en Cinéma & Audiovisuel',
                        'etablissement'    => 'EDAC',
                        'ville'            => 'Tunis',
                        'duree'            => '3 ans',
                        'niveau'           => 'Licence',
                        'description'      => 'Réalisation, scénario, montage, production audiovisuelle et nouvelles écritures numériques pour le cinéma, la télévision et le streaming.',
                        'debouches'        => 'Réalisateur, Monteur, Producteur, Scénariste, Créateur de contenu.',
                        'conditions_acces' => 'Baccalauréat toutes séries. Short-film ou portfolio + entretien.',
                        'salaire_min'      => '1 000 DT',
                        'salaire_max'      => '3 500 DT',
                        'secteur'          => 'Audiovisuel / OTT',
                        'icon'             => '🎬',
                        'score_matching'   => 65,
                    ],
                ],
            ],
            [
                'specialite' => [
                    'nom'         => 'Droit & Sciences Juridiques',
                    'description' => 'Étude du droit civil, pénal, commercial et international pour exercer dans la justice, le conseil ou l\'entreprise.',
                    'domaine'     => 'Droit',
                    'icon'        => '⚖️',
                    'color'       => 'indigo',
                ],
                'formations' => [
                    [
                        'nom'              => 'Licence en Droit Privé',
                        'etablissement'    => 'Faculté de Droit Tunis',
                        'ville'            => 'Tunis',
                        'duree'            => '3 ans',
                        'niveau'           => 'Licence',
                        'description'      => 'Droit civil des obligations et des contrats, droit de la famille, droit commercial tunisien et introduction au droit international privé.',
                        'debouches'        => 'Avocat (après barreau), Notaire, Juriste d\'entreprise, Greffier.',
                        'conditions_acces' => 'Baccalauréat toutes séries. Admis sur dossier, très accessible.',
                        'salaire_min'      => '1 200 DT',
                        'salaire_max'      => '5 000 DT',
                        'secteur'          => 'Justice / Entreprise',
                        'icon'             => '📜',
                        'score_matching'   => 69,
                    ],
                    [
                        'nom'              => 'Master en Droit des Affaires',
                        'etablissement'    => 'FDSPT',
                        'ville'            => 'Tunis',
                        'duree'            => '2 ans',
                        'niveau'           => 'Master',
                        'description'      => 'Droit des sociétés, fusions-acquisitions, propriété intellectuelle, fiscalité d\'entreprise et arbitrage commercial international.',
                        'debouches'        => 'Avocat d\'affaires, Juriste M&A, Compliance officer, Conseiller juridique.',
                        'conditions_acces' => 'Licence en droit. Dossier académique + entretien.',
                        'salaire_min'      => '2 200 DT',
                        'salaire_max'      => '6 000 DT',
                        'secteur'          => 'Finance / Multinationales',
                        'icon'             => '🤝',
                        'score_matching'   => 74,
                    ],
                    [
                        'nom'              => 'Licence en Droit Public',
                        'etablissement'    => 'Faculté de Droit Sfax',
                        'ville'            => 'Sfax',
                        'duree'            => '3 ans',
                        'niveau'           => 'Licence',
                        'description'      => 'Droit constitutionnel, droit administratif, droits de l\'homme, finances publiques et droit international public.',
                        'debouches'        => 'Fonctionnaire, Magistrat (après ENA), Diplomate, Juriste collectivités.',
                        'conditions_acces' => 'Baccalauréat toutes séries. Admission sur dossier.',
                        'salaire_min'      => '1 100 DT',
                        'salaire_max'      => '3 500 DT',
                        'secteur'          => 'Administration / Diplomatie',
                        'icon'             => '🏛️',
                        'score_matching'   => 63,
                    ],
                ],
            ],
            [
                'specialite' => [
                    'nom'         => 'Sciences de l\'Éducation & Enseignement',
                    'description' => 'Formation aux méthodologies pédagogiques, psychologie de l\'apprentissage et gestion de classe pour les futurs enseignants et formateurs.',
                    'domaine'     => 'Éducation',
                    'icon'        => '🎓',
                    'color'       => 'green',
                ],
                'formations' => [
                    [
                        'nom'              => 'Licence en Sciences de l\'Éducation',
                        'etablissement'    => 'ISEFC',
                        'ville'            => 'Tunis',
                        'duree'            => '3 ans',
                        'niveau'           => 'Licence',
                        'description'      => 'Psychologie de l\'éducation, didactique des disciplines, évaluation des apprentissages, technologies éducatives et ingénierie de formation.',
                        'debouches'        => 'Enseignant, Formateur, Conseiller pédagogique, Coach éducatif, Concepteur e-learning.',
                        'conditions_acces' => 'Baccalauréat toutes séries. Admission sur dossier.',
                        'salaire_min'      => '1 000 DT',
                        'salaire_max'      => '2 500 DT',
                        'secteur'          => 'Éducation / Formation',
                        'icon'             => '📚',
                        'score_matching'   => 66,
                    ],
                    [
                        'nom'              => 'Master en Ingénierie Pédagogique',
                        'etablissement'    => 'ISEFC',
                        'ville'            => 'Tunis',
                        'duree'            => '2 ans',
                        'niveau'           => 'Master',
                        'description'      => 'Conception de dispositifs de formation professionnelle, e-learning, MOOC, évaluation des compétences et management de la formation continue.',
                        'debouches'        => 'Responsable formation, Ingénieur pédagogique, Concepteur MOOC, DRH.',
                        'conditions_acces' => 'Licence en éducation, psychologie ou RH. Entretien.',
                        'salaire_min'      => '1 500 DT',
                        'salaire_max'      => '3 500 DT',
                        'secteur'          => 'Entreprise / Institutions',
                        'icon'             => '🧑‍🏫',
                        'score_matching'   => 68,
                    ],
                    [
                        'nom'              => 'Licence en Langue & Littérature Française',
                        'etablissement'    => 'Faculté des Lettres Manouba',
                        'ville'            => 'La Manouba',
                        'duree'            => '3 ans',
                        'niveau'           => 'Licence',
                        'description'      => 'Langue française, littérature francophone, linguistique, traduction et communication culturelle. Excellente maîtrise du français écrit et oral.',
                        'debouches'        => 'Professeur de français, Traducteur, Journaliste, Rédacteur de contenu, Attaché culturel.',
                        'conditions_acces' => 'Baccalauréat toutes séries. Très accessible.',
                        'salaire_min'      => '900 DT',
                        'salaire_max'      => '2 800 DT',
                        'secteur'          => 'Enseignement / Médias',
                        'icon'             => '📖',
                        'score_matching'   => 61,
                    ],
                ],
            ],
        ];

        foreach ($data as $item) {
            $specialite = Specialite::create(array_merge(
                $item['specialite'],
                ['nb_formations' => count($item['formations'])]
            ));

            foreach ($item['formations'] as $f) {
                Formation::create(array_merge($f, ['specialite_id' => $specialite->id]));
            }
        }
    }
}
